project_name: cs
builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: '{{.ProjectName}}-{{.Tag}}-checksums.txt'